from celery import shared_task
from .models import LogEntry, ChatEntry, IssueCluster


from .services.ai_service import AIService


@shared_task
def process_new_log_entry(log_id):
    try:
        log = LogEntry.objects.get(id=log_id)
        # Simple heuristic or clustering hook
        if log.level == 'ERROR':
            print(f"Processing ERROR log: {log.message}")
            # In real implementation: AIService.cluster_issues([log.message])
    except LogEntry.DoesNotExist:
        pass


@shared_task
def process_new_chat_entry(chat_id):
    try:
        chat = ChatEntry.objects.get(id=chat_id)
        
        # Sentiment Analysis
        sentiment = AIService.analyze_sentiment(chat.message)
        chat.sentiment_score = sentiment
        chat.save()
        print(f"Processed chat {chat.id}: Sentiment={sentiment}")
        
    except ChatEntry.DoesNotExist:
        pass


@shared_task
def poll_chat_sources():
    # TODO: Implement polling logic for WhatsApp/Freshchat
    print("Polling chat sources...")


@shared_task
def run_clustering_task():
    # Fetch unclustered chats
    # For simplicy, fetch last 100 unprocessed
    chats = ChatEntry.objects.filter(processed=False)[:100]
    if not chats:
        return
    
    texts = [c.message for c in chats]
    labels = AIService.cluster_issues(texts)
    
    # Process labels
    # -1 is noise
    # 0, 1, 2... are clusters
    # Logic to create/update IssueCluster
    for label in set(labels):
        if label == -1:
            continue
        
        # Determine theme for this cluster
        cluster_texts = [texts[i] for i, l in enumerate(labels) if l == label]
        theme = f"Cluster {label}: {cluster_texts[0][:20]}..."
        
        cluster, created = IssueCluster.objects.get_or_create(theme=theme)
        cluster.frequency = len(cluster_texts)
        cluster.description = "Generated by AI"
        cluster.sentiment_score = 0.0  # TODO: aggregare
        cluster.save()
        
        # Mark processed
        # In real logic, we link chat to cluster
    
    print(f"Clustering complete. Found {len(set(labels)) - (1 if -1 in labels else 0)} clusters.")

